# --- GESTIONE ENERGIA DONGLE ---
# Il dongle è alimentato via USB, non deve mai spegnersi
CONFIG_ZMK_SLEEP=n

# Spegne la UI nativa di ZMK
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=n

# Attiva l'interfaccia YADS (già configurata per display ST7789 SPI)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DISPLAY=y

# Se nel case del Prospector hai montato anche il sensore di luce APDS9960, scommenta questa riga:
# CONFIG_DONGLE_SCREEN_SENSOR=y

# Forza il Dongle a richiedere lo stato della batteria alle due metà
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
