# --- CONFIGURAZIONE ESCLUSIVA PER IL DONGLE ---

# Definisce che questo chip è il modulo centrale (Master/Dongle)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Abilita il supporto split 
CONFIG_ZMK_SPLIT=y

# Ora che il ruolo central è confermato, questa variabile sarà valida
CONFIG_ZMK_SPLIT_BLE_PERIPHERAL_COUNT=2
