# Copyright (c) 2021-2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Enable mouse emulation.
CONFIG_ZMK_POINTING=y

# Impostazioni dello schermo comuni
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
